target=griffpi-static
ssh_key=~/.ssh/claude_pi
ssh_user=chris
ssh_host=griffpi
build_cmd=hugo --minify
build_output=public/
remote_path=/var/www/gwefan/
remote_owner=chris:chris
pre_deploy=scripts/update-stats.sh
